"""Added Field For Storing Encrypted GitHub User Token

Revision ID: 1ab30933277e
Revises: 6d505584380c
Create Date: 2025-01-21 20:25:44.034216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ab30933277e'
down_revision = '6d505584380c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encrypted_token', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_token')
    # ### end Alembic commands ###
