"""Added Contributor model

Revision ID: 5e3611667a29
Revises: 11173fdeb5d8
Create Date: 2025-02-03 10:00:03.611306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e3611667a29'
down_revision = '11173fdeb5d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contributor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('contributor_name', sa.String(length=255), nullable=False),
    sa.Column('commit_count', sa.Integer(), nullable=True),
    sa.Column('lines_added', sa.Integer(), nullable=True),
    sa.Column('lines_removed', sa.Integer(), nullable=True),
    sa.Column('last_contributed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contributor')
    # ### end Alembic commands ###
